# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 15:08
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


def drop_all_persons(apps, schema_editor):
    """
    There is no real data here yet, we can just drop empty persons
    """
    apps.get_model('persons', 'person').objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='primary_name',
        ),
        migrations.AddField(
            model_name='person',
            name='names',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128),
                default=['I will be deleted'],
                size=None
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.RunPython(drop_all_persons, migrations.RunPython.noop),
    ]
