# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-29 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0002_day_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['date']},
        ),
    ]
