# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-30 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0003_ordering_by_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='id',
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(primary_key=True, serialize=False, unique=True),
        ),
    ]
